tasks:

  unit-test:

    runner: razorci/openjdk:11-buster

    steps:

    - checkout

    - commands:

      - |

        mvn clean package

           ls -a

    - docker/build:

         image: razoropscode.jfrog.io/docker/spring

         push: true 

         tags: ["latest-v1"]

