version: v2
tasks:
  build:
    runner: razorci/python:3.9
    steps:
    - checkout
    
    - commands: 
      - python -c 'import site; print(site.getsitepackages())'
      - pip install -r requirements.txt
      - |

        mvn clean package

           ls -a
    - commands:
      - python test.py

    # build and push a Docker image. You will need to add the credentials in Dashboard
    - docker/build:
        image: teamprojectt.jfrog.io/docker/sahitiputcha/new_file_python
        tags: ["${CI_COMMIT_SHA:0:8}", "${CI_REPO_BRANCH}", "latest"]
        dockerfile: Dockerfile
        context: hack
        push: true
